version: 6 (50.0)
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      target: dev
    restart: always
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
